"""
LLM scoring helper for $JOB using Google Gemini (google-genai SDK).

Design principles:
  - Gemini produces: rating, scores, oneLineVerdict, bullCase, bearCase,
                     recommendation, alternatives, debugSignals
  - Python produces deterministically: ticker, chartData
  - _validate_and_patch enforces all frontend contracts (array lengths,
    score-rating consistency, type safety, risk normalization)
  - Sources are never requested from or trusted from the LLM
"""

import asyncio
import hashlib
import json
import logging
import os
import random
import re
import threading

from google import genai
from google.genai import types

logger = logging.getLogger(__name__)

GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY", "")
MODEL = "gemini-2.5-flash"

MONTH_NAMES = ["May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar", "Apr"]

RISK_MAP = {
    "low": "Low", "medium": "Medium", "high": "High",
    "very high": "High", "moderate": "Medium", "minimal": "Low",
}

DEFAULT_ALTS = [
    {"label": "Stay 6 months",        "description": "Assess trajectory before committing long-term.", "risk": "Low"},
    {"label": "Join a competitor",    "description": "Explore adjacent opportunities in the market.",  "risk": "Medium"},
    {"label": "Start your own thing", "description": "Leverage your network and expertise independently.", "risk": "High"},
]

# ── Deterministic generators ─────────────────────────────────────────────────

def make_ticker(company: str, role: str) -> str:
    """Always generated in Python — never trusted from LLM output."""
    company_part = "".join(w[0] for w in company.split()[:2]).upper() or company[:3].upper()
    role_part    = "".join(w[0] for w in role.split()[:2]).upper()    or role[:2].upper()
    return f"{company_part}-{role_part}"


def generate_chart(company: str, role: str, rating: str) -> list:
    """
    Noise seeded by (company, role) only — same pair always produces the same
    random sequence regardless of rating. Trend direction is applied on top of
    the fixed noise, so charts for the same (company, role, rating) triple are
    always identical, and only the trend shifts when rating changes.
    """
    seed = int(hashlib.md5(f"{company}{role}".encode()).hexdigest(), 16) % (2 ** 31)
    rng  = random.Random(seed)
    trend_map = {"BUY": 1.8, "HOLD": 0.3, "SELL": -1.2, "SHORT": -2.8}
    monthly_trend = trend_map.get(rating, 0.3)
    price  = 100.0
    result = []
    for month in MONTH_NAMES:
        price = max(1.0, price + monthly_trend + rng.gauss(0, 3))
        result.append({"month": month, "price": round(price, 1)})
    return result


# ── Prompt builders ──────────────────────────────────────────────────────────

SYSTEM_PROMPT = """You are a sharp, data-grounded career analyst who prices jobs like financial assets.
Given research signals about a company and role, produce a synthetic stock analysis in strict JSON.
Be concise, insightful, and slightly provocative — this is a hackathon product called $JOB.

CONSTRAINTS (mandatory):
- Never invent salary figures, funding amounts, or company facts not present in the data sections.
- debugSignals must only paraphrase information from the data sections provided.
- Do NOT generate sources — they are provided separately.
- Do NOT generate a ticker — it will be set by the system.
- Do NOT generate chartData — it will be generated by the system.
- Keep recommendation to exactly 2 sentences.
- bullCase and bearCase must each have exactly 3 items.
- alternatives.risk must be exactly "Low", "Medium", or "High" — nothing else.
- Return only valid JSON. No markdown, no code fences."""

# The schema Gemini is asked to fill — ticker and chartData intentionally excluded
RESPONSE_SCHEMA = """{
  "rating": "BUY" | "HOLD" | "SELL" | "SHORT",
  "oneLineVerdict": "<one punchy sentence>",
  "scores": {
    "momentum": <0-100>,
    "salaryYield": <0-100>,
    "volatility": <0-100>,
    "upside": <0-100>
  },
  "bullCase": ["<string>", "<string>", "<string>"],
  "bearCase": ["<string>", "<string>", "<string>"],
  "recommendation": "<exactly 2 sentences>",
  "alternatives": [
    {"label": "Stay 6 months", "description": "<string>", "risk": "Low"},
    {"label": "Join a competitor", "description": "<string>", "risk": "Medium"},
    {"label": "Start your own thing", "description": "<string>", "risk": "High"}
  ],
  "debugSignals": {
    "companySummary": "<string>",
    "newsSignals": ["<string>"],
    "hiringSignals": ["<string>"],
    "riskSignals": ["<string>"]
  }
}"""

SCORING_RUBRIC = """
SCORING RUBRIC — derive scores from data above; default to 50 when signals are absent or unclear

momentum (0-100, company trajectory):
  >70: recent funding confirmed OR HN job posts >20 OR clear active growth signals in news
  40-70: mixed or absent signals
  <40: hiring freeze / restructuring language in recent news
  <25: layoffs confirmed OR ycStatus=Dead OR insolvency notice

salaryYield (0-100, compensation quality for this role):
  >70: above-market salary data confirmed (stepstone/glassdoor/levels.fyi) OR
       Bundesagentur vacancies >500 (high market demand = candidate leverage)
  40-70: salary data absent or at-market
  <40: below-market signals from kununu/glassdoor reviews

volatility (0-100, uncertainty / stability):
  >70: SEC 8-K filings >3 in 12mo OR active restructuring in news OR insolvency notice
  40-70: some mixed signals, moderate uncertainty
  <40: stable, profitable, low news volume, long operating history

upside (0-100, growth / equity potential):
  >70: pre-IPO signals OR recent funding up-round OR YC active batch
  40-70: steady company, career capital value but limited near-term equity
  <40: mature company capped equity OR ycStatus=Dead OR declining market signals

RATING DERIVATION:
  BUY:   momentum>=70 AND upside>=65 AND volatility<75
  HOLD:  momentum 40-69 OR (high upside offset by high volatility) — DEFAULT when uncertain
  SELL:  momentum<45 AND salaryYield<55
  SHORT: momentum<35 AND volatility>70 AND (layoffs confirmed OR ycStatus=Dead OR insolvency)
  When in doubt: HOLD
"""


def _render_availability(ctx: dict, role: str) -> str:
    def yn(flag: str) -> str:
        return "YES" if ctx.get(flag) else "NO"

    yc_line = (
        f"FOUND batch={ctx['ycBatch']} status={ctx['ycStatus']}"
        if ctx.get("hasYcData") and ctx.get("ycStatus") != "unknown"
        else "NOT FOUND"
    )
    hn_line = (
        f"{ctx['hnJobPostCount']} job postings (0 may mean company does not recruit via HN, not that they are not hiring)"
        if ctx.get("hasHnData")
        else "NOT FOUND"
    )
    sec_line = (
        f"{ctx['secFilingCount']} 8-K/10-K filings since 2024"
        if ctx.get("hasSecData") and ctx.get("secFilingCount")
        else "0 filings — private company (neutral, not low-volatility signal)"
        if ctx.get("hasSecData")
        else "NOT FOUND"
    )
    ba_line = (
        f"{ctx['bundesagenturVacancies']} open {role!r} roles in Germany — "
        "IMPORTANT: this is MARKET-WIDE demand for the role type, NOT company-specific hiring"
        if ctx.get("hasBundesagenturData")
        else "NOT FOUND"
    )
    hr_line = (
        f"status={ctx['handelsregisterStatus']} founded={ctx['handelsregisterFounded']}"
        + (" ⚠ INSOLVENCY NOTICE FOUND" if ctx.get("handelsregisterInsolvency") else "")
        if ctx.get("hasHandelsregisterData")
        else "NOT CHECKED"
    )

    return f"""DATA AVAILABILITY — calibrate your confidence to this
  Funding/business data:       {yn('hasFundingData')}
  Recent news (last 30 days):  {yn('hasRecentNews')}
  Salary/compensation data:    {yn('hasSalaryData')} (stepstone.de, glassdoor, levels.fyi)
  Hiring/jobs data:            {yn('hasHiringData')} (xing.com, greenhouse, linkedin)
  Culture/sentiment data:      {yn('hasSentimentData')} (kununu.com, glassdoor)
  YC registry:                 {yc_line}
  HN job posts:                {hn_line}
  SEC filings (US public cos): {sec_line}
  German job market (BA):      {ba_line}
  Handelsregister (DE):        {hr_line}

When a section is NO or NOT FOUND: use your training knowledge but reflect uncertainty
in the relevant score (bias toward 50) and add the gap to your bear case."""


def _render_section(label: str, answer: str, snippets: list, extracts=None) -> str:
    lines = [f"\n{label}"]
    if answer:
        lines.append(answer)
    for s in snippets:
        lines.append(f"  • {s}")
    if extracts:
        for e in extracts:
            lines.append(f"\n  --- SOURCE: {e['url']} ---")
            lines.append(f"  {e['content'][:800]}")
    return "\n".join(lines)


def _build_prompt(company: str, role: str, ctx: dict) -> str:
    sections = [
        f"COMPANY: {company}\nROLE: {role}\n",
        _render_availability(ctx, role),
    ]

    if ctx.get("hasFundingData"):
        sections.append(_render_section(
            "FINANCIAL & BUSINESS SIGNALS",
            ctx.get("fundingAnswer", ""),
            ctx.get("fundingSnippets", []),
            ctx.get("fundingExtracts", []),
        ))
    else:
        sections.append("\nFINANCIAL & BUSINESS SIGNALS\nNOT AVAILABLE — use training knowledge")

    if ctx.get("hasRecentNews"):
        sections.append(_render_section(
            "RECENT NEWS (last 30 days)",
            ctx.get("newsAnswer", ""),
            ctx.get("newsSnippets", []),
        ))
    else:
        sections.append("\nRECENT NEWS\nNOT AVAILABLE — use training knowledge")

    if ctx.get("hasSalaryData"):
        sections.append(_render_section(
            "COMPENSATION DATA",
            ctx.get("salaryAnswer", ""),
            ctx.get("salarySnippets", []),
        ))
    else:
        sections.append("\nCOMPENSATION DATA\nNOT AVAILABLE — use training knowledge, default salaryYield to 50")

    if ctx.get("hasHiringData"):
        sections.append(_render_section(
            "HIRING VELOCITY",
            ctx.get("hiringAnswer", ""),
            ctx.get("hiringSnippets", []),
        ))
    else:
        sections.append("\nHIRING VELOCITY\nNOT AVAILABLE — use training knowledge")

    if ctx.get("hasSentimentData"):
        sections.append(_render_section(
            "CULTURE & SENTIMENT",
            ctx.get("sentimentAnswer", ""),
            ctx.get("sentimentSnippets", []),
        ))
    else:
        sections.append("\nCULTURE & SENTIMENT\nNOT AVAILABLE — use training knowledge")

    sections.append(SCORING_RUBRIC)
    sections.append(f"\nReturn ONLY valid JSON matching this schema (no markdown, no extra fields):\n{RESPONSE_SCHEMA}")

    return "\n".join(sections)


# ── Validation ───────────────────────────────────────────────────────────────

def _validate_and_patch(data: dict, company: str, role: str) -> dict:
    """
    Enforce all frontend contracts deterministically after LLM parsing.
    Never raises — always returns a complete, consistent response.
    """
    # 1. Ticker — always deterministic Python
    data["ticker"] = make_ticker(company, role)

    # 2. Rating — must be in allowed set
    if data.get("rating") not in {"BUY", "HOLD", "SELL", "SHORT"}:
        data["rating"] = "HOLD"

    # 3. Scores — defensive float parsing (handles null, "N/A", strings gracefully)
    scores = data.get("scores") or {}
    if not isinstance(scores, dict):
        scores = {}
    for key in ["momentum", "salaryYield", "volatility", "upside"]:
        raw = scores.get(key)
        try:
            val = int(float(raw))
        except (TypeError, ValueError):
            val = 50   # neutral — never raise
        scores[key] = max(0, min(100, val))
    data["scores"] = scores

    # 4. Score-to-rating consistency matrix — prevents BUY+momentum=30 contradictions
    rating = data["rating"]
    if rating == "BUY":
        scores["momentum"] = max(scores["momentum"], 55)
        scores["upside"]   = max(scores["upside"],   60)
    elif rating == "SHORT":
        scores["momentum"] = min(scores["momentum"], 40)
        scores["upside"]   = min(scores["upside"],   35)
    elif rating == "SELL":
        scores["momentum"] = min(scores["momentum"], 60)

    # 5. chartData — fully deterministic (company + role + rating only, no LLM floats)
    data["chartData"] = generate_chart(company, role, rating)

    # 6. bullCase / bearCase — enforce exactly 3 strings
    placeholder = "Insufficient data to determine additional signals."
    for field in ["bullCase", "bearCase"]:
        arr = data.get(field)
        if not isinstance(arr, list):
            arr = [str(arr)] if arr else []
        arr = [str(item) for item in arr]
        while len(arr) < 3:
            arr.append(placeholder)
        data[field] = arr[:3]

    # 7. recommendation — exactly 2 sentences, enforced
    rec = str(data.get("recommendation") or "")
    sentences = [s.strip() for s in re.split(r"[.!?]", rec) if s.strip()]
    if sentences:
        data["recommendation"] = ". ".join(sentences[:2]) + "."
    else:
        data["recommendation"] = "Assess this role carefully before committing. Monitor company signals over the next quarter."

    # 8. alternatives — exactly 3 items with valid risk values
    alts = data.get("alternatives")
    if not isinstance(alts, list):
        alts = []
    normalized = []
    for alt in alts:
        if not isinstance(alt, dict):
            continue
        raw_risk = str(alt.get("risk", "")).lower().strip()
        alt["risk"] = RISK_MAP.get(raw_risk, "Medium")
        normalized.append(alt)
    while len(normalized) < 3:
        normalized.append(DEFAULT_ALTS[len(normalized)])
    data["alternatives"] = normalized[:3]

    # 9. debugSignals — ensure all expected keys exist
    ds = data.get("debugSignals") or {}
    if not isinstance(ds, dict):
        ds = {}
    ds.setdefault("companySummary", "")
    ds.setdefault("newsSignals",    [])
    ds.setdefault("hiringSignals",  [])
    ds.setdefault("riskSignals",    [])
    data["debugSignals"] = ds

    # 10. Remove sources if LLM hallucinated any — sources always come from Tavily
    data.pop("sources", None)

    return data


# ── Main entry point ─────────────────────────────────────────────────────────

def score_job(company: str, role: str, ctx: dict) -> dict:
    """
    Call Gemini to produce a structured job stock analysis.
    Raises on API/parse error — caller should catch and use fallback.
    """
    if not GOOGLE_API_KEY:
        raise ValueError("GOOGLE_API_KEY not set")

    client = genai.Client(api_key=GOOGLE_API_KEY)
    prompt = _build_prompt(company, role, ctx)

    response = client.models.generate_content(
        model=MODEL,
        contents=prompt,
        config=types.GenerateContentConfig(
            system_instruction=SYSTEM_PROMPT,
            temperature=1.0,              # required when thinking is enabled
            response_mime_type="application/json",
            thinking_config=types.ThinkingConfig(
                thinking_budget=1500,
                include_thoughts=False,   # keep response.text as clean JSON
            ),
        ),
    )

    raw = response.text.strip()
    # Strip markdown code fences if model ignores mime type hint
    raw = re.sub(r"^```(?:json)?\s*", "", raw)
    raw = re.sub(r"\s*```$", "", raw)

    parsed = json.loads(raw)
    return _validate_and_patch(parsed, company, role)


# ── streaming variant ─────────────────────────────────────────────────────────

def _score_job_stream_sync(company: str, role: str, ctx: dict):
    """
    Synchronous generator. Yields {"type":"thinking","text":...} for each
    Gemini thought chunk, then {"type":"result","data":{...}} when done.
    Designed to run inside a worker thread.
    Raises on API/parse error.
    """
    if not GOOGLE_API_KEY:
        raise ValueError("GOOGLE_API_KEY not set")

    client = genai.Client(api_key=GOOGLE_API_KEY)
    prompt = _build_prompt(company, role, ctx)
    content_buf: list[str] = []

    for chunk in client.models.generate_content_stream(
        model=MODEL,
        contents=prompt,
        config=types.GenerateContentConfig(
            system_instruction=SYSTEM_PROMPT,
            temperature=1.0,
            response_mime_type="application/json",
            thinking_config=types.ThinkingConfig(
                thinking_budget=1500,
                include_thoughts=True,  # we separate thought vs content parts
            ),
        ),
    ):
        if not chunk.candidates:
            continue
        for part in chunk.candidates[0].content.parts:
            if getattr(part, "thought", False):
                if part.text:
                    yield {"type": "thinking", "text": part.text}
            else:
                if part.text:
                    content_buf.append(part.text)

    raw = "".join(content_buf).strip()
    raw = re.sub(r"^```(?:json)?\s*", "", raw)
    raw = re.sub(r"\s*```$", "", raw)

    parsed = json.loads(raw)
    result = _validate_and_patch(parsed, company, role)
    yield {"type": "result", "data": result}


async def score_job_stream_async(company: str, role: str, ctx: dict):
    """
    Async generator. Bridges _score_job_stream_sync (which blocks) to async
    via asyncio.Queue + a daemon thread.
    Yields {"type":"thinking","text":...} then {"type":"result","data":{...}}.
    On error yields {"type":"error","message":str}.
    """
    loop = asyncio.get_event_loop()
    q: asyncio.Queue = asyncio.Queue()
    _DONE = object()

    def _thread():
        try:
            for event in _score_job_stream_sync(company, role, ctx):
                loop.call_soon_threadsafe(q.put_nowait, event)
        except Exception as e:
            loop.call_soon_threadsafe(q.put_nowait, {"type": "error", "message": str(e)})
        finally:
            loop.call_soon_threadsafe(q.put_nowait, _DONE)

    threading.Thread(target=_thread, daemon=True).start()

    while True:
        item = await q.get()
        if item is _DONE:
            break
        yield item
